services:
  - type: web
    name: fmcg-supply-chain-dashboard
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /dashboard/dashboard.html
